name: test matrix
on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        include:
        - os: macos-latest
        - os: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        
      - name: 'run shellspec tests'
        run: |
            mkdir .install
            curl -fsSL https://git.io/shellspec | sh -s -- -p $PWD/.install --yes
            $PWD/.install/bin/shellspec
